query = ws* expr ws*

expr = not ws* expr
		 | lparen ws* expr ws* rparen 
		 | expr ws* bool ws* expr
		 | expr ws* bool ws* oper
		 | oper ws* bool ws* expr
		 | oper ws* bool ws* oper
		 | oper

oper = value ws* eq ws* value
		 | value ws* ltgt ws* value
		 | value ws* contains ws* value
		 | value ws* like ws* value
		 | value 

eq = '=' | '<>'
ltgt = '>=' | '<=' | '>' | '<'  
bool = 'and' | 'or'
not = 'not'
contains = 'contains'
like = 'like'

value = string | var | integer
integer = #'[0-9]+'
string = <'"'> #'[^\"]+' <'"'>
var = #'[a-zA-Z\+-]([0-9a-zA-Z\+-]*)'

<lparen> = <"(">
<rparen> = <")">
<ws> = <#'[ \t\n,]+'>
